$(document).ready(function() {
    $("#tabelaCoordenadas").DataTable({
        data: dadosRelatorioCoordenada,
        responsive: true,
        ordering: false,
        paging: true,
        searching: true,
        info: true,
        language: lang.datatable,
        deferRender: true,
        lengthChange: false,
        bSort: false,
        dom: "Bfrtip",
        buttons: [
            {
                extend: "excelHtml5",
                text: "Excel",
                className: 'btn btn-primary',
            },
            {
                extend: "pdfHtml5",
                exportOptions: {
                    columns: ":visible",
                },
                text: "PDF",
                orientation: "landscape",
                pageSize: "A1",
                className: 'btn btn-primary',
            },
            {
                extend: 'csvHtml5',
                exportOptions: {
                    columns: ':visible'
                },
                orientation: 'landscape',
                pageSize: 'LEGAL',
                className: 'btn btn-primary',
            },
        ],
        columns: [
            { data: "base" },
            { data: "botaoPanico" },
            { data: "data" },
            { data: "dataSys" },
            { data: "direcao" },
            { data: "localizacao.endereco" },
            { data: "localizacao.latitude" },
            { data: "localizacao.longitude" },
            { data: "engateCarreta" },
            { data: "estado" },
            { data: "teleEvento" },
            { data: "odometro" },
            { data: "tipoComunicacao" },
            { data: "ignicao" },
            { data: "intervaloTransmissao" },
            { data: "lacreBau" },
            { data: "motorista" },
            { data: "placa" },
            { data: "prefixoVeiculo" },
            { data: "rpm" },
            { data: "statusGps" },
            { data: "statusPosicao" },
            { data: "falhaTravaMotorista" },
            { data: "temperaturas" },
            { data: "horimetro" },
            { data: "umidade" },
            { data: "velocidade" },
            { data: "voltagem" },
            { data: "serial" },
            { data: "out1" },
            { data: "out2" }
        ],
    });
});