ALTER TABLE `showtecsystem`.`cad_permissoes_funcionarios`
ADD COLUMN `modulo` VARCHAR(45) NOT NULL AFTER `data_cad`;

ALTER TABLE `showtecsystem`.`cad_cargo`
ADD COLUMN `permissoes` TEXT NOT NULL AFTER `data_cad`;


DROP TABLE showtecsystem.cad_cargo_modulo_funcionario;
DROP TABLE showtecsystem.cad_modulo_permissao_funcionario;
DROP TABLE showtecsystem.cad_modulos_funcionarios;


DELETE FROM `showtecsystem`.`cad_permissoes_funcionarios`;

INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`, `modulo`)
VALUES
('documentacoes','Documentações', 'Cadastros'),
('licitacoes','Licitações', 'Cadastros'),
('cad_veiculos','Veículos', 'Cadastros'),
('cad_permissoes','Permissões (GESTOR)', 'Cadastros'),
('cad_planos', 'Planos (GESTOR)', 'Cadastros'),
('administrar_veiculos','Administrar Veículos', 'Cadastros'),
('cad_permissoes_funcionarios','Cadastro de permissões de funcionarios', 'Cadastros'),
('cad_equipamento','Equipamentos', 'Cadastros'),
('cad_contratos_eptc','Contratos EPTC', 'Cadastros'),
('cad_agend_servico','Agendamento de Serviços', 'Cadastros'),
('cad_instaladores','Instaladores', 'Cadastros'),
('cad_representantes','Representantes', 'Cadastros'),
('cad_comandos','Comandos', 'Cadastros'),
('cad_centrais', 'Centrais MHS', 'Cadastros'),

('cadastro_fornecedor','Fornecedores', 'Cadastros'),
('clientes_visualiza','Visualizar', 'Visualizar'),
('clientes_add','Adicionar', 'Visualizar'),
('clientes_update','Atualizar', 'Visualizar'),
('inativa_clie','Inativar', 'Visualizar'),
('clientes_bloqueio','Bloqueio usuário', 'Visualizar'),
('clientes_arquivo','Download Arquivos', 'Visualizar'),
('usuarios_visualiza','Visualizar', 'Funcionários'),
('usuarios_add','Adicionar', 'Funcionários'),
('usuarios_update','Atualizar', 'Funcionários'),
('status_funcionario','Status funcionario', 'Funcionários'),
('aplicar_ferias','Aplicar ferias', 'Funcionários'),
('demitir','Demitir', 'Funcionários'),
('m2m','M2M', 'Funcionários'),
('crm_vendas','crm_vendas', 'CRM DE VENDAS'),
('crm_vendas_admin','Administrador', 'CRM DE VENDAS'),
('cad_linhas','Linhas', 'Linhas'),
('cad_mikrotik','MikroTik', 'Linhas'),
('cad_chips','Chips', 'Linhas'),
('cad_rh','RH', 'RH'),
('cad_aniversariantes','Aniversariantes', 'RH'),
('cad_apresentacoes','Apresentações', 'RH'),
('cad_banner','Banner', 'RH'),
('cad_comunicado','Comunicados', 'RH'),
('cad_contatos_corporativos','Contatos Corporativos', 'RH'),
('cad_folhetos','Folhetos', 'RH'),
('cad_sobre_empresa','Sobre a empresa', 'RH'),
('cad_politicas_formularios','Políticas', 'RH'),
('cad_produtos','Produtos', 'RH'),
('cad_suporte_tecnico','Suporte Técnico', 'Engenharia e Tecnologia'),
('cad_teste_homologacao','Teste e Homologação', 'Engenharia e Tecnologia'),
('cad_espaco_ti','Espaço TI', 'Espaço TI'),
('cad_marketing_briefing','Briefing', 'Marketing'),
('cad_marketing_campanhas','Campanhas', 'Marketing'),
('cad_apresentacoes_comerciais','Apresentações Comerciais', 'Televendas'),
('cad_comite_guerra','Comitê de Guerra', 'Televendas'),
('cad_televendas_comunicados','Comunicados', 'Televendas'),
('cad_propostas_comerciais','Propostas Comerciais', 'Televendas'),
('cad_politicas_procedimentos','Políticas e Procedimentos', 'Televendas'),
('cad_guia_produtos','Guia de Produtos', 'Televendas'),
('cad_precos_acessorios','Tabela de Preços e Acessórios', 'Televendas'),
('cad_inteligencia_mercado','Inteligência de Mercado', 'Televendas'),
('cad_governanca_corporativa','Governança Corporativa', 'Governança Corporativa'),
('cad_gente_gestao','Gente e gestão', 'Espaço Gente & Gestao'),
('cad_treinamentos','Treinamentos EAD', 'Espaço Gente & Gestao'),
('cad_atividades','Cad Treinamentos', 'Espaço Gente & Gestao'),
('cad_parcerias','Parcerias', 'Espaço Gente & Gestao'),
('cad_plano_de_voo','Plano de Voo', 'Espaço Gente & Gestao'),
('cad_correcao_irrf','Correção de IRRF', 'Espaço Gente & Gestao'),
('cad_docs_pendentes','Documentos Pendentes', 'Espaço Gente & Gestao'),
('cad_desconto_coparticipacao','Desconto de Coparticipação', 'Espaço Gente & Gestao'),
('rel_tipo_servico','Tipo de Serviços', 'Relatórios'),
('rel_veic_tempo_contrato','Veículo por Tempo de Contrato', 'Relatórios'),
('rel_clients_publicos','Clientes Públicos', 'Relatórios'),
('rel_contas','Contas a Pagar', 'Relatórios'),
('rel_contratos','Contratos', 'Relatórios'),
('rel_placas_ativas_inativas','Placas Ativas - Inativas', 'Relatórios'),
('rel_tempo_logado','Tempo logado', 'Relatórios'),
('rel_envio_sms','Envio SMS', 'Relatórios'),
('rel_eqp_desat','Equipamentos Desatualizados', 'Relatórios'),
('analise_contaOp','Analise de Fatura Operadora', 'Relatórios'),
('rel_financeiro_faturas','Faturas', 'Relatórios'),
('comissao','Comissionamento de Vendedores', 'Relatórios'),
('comissao_showroutes','Comissionamento - ShowRoutes', 'Relatórios'),
('rel_adesao','Relatorio de adesao', 'Relatórios'),
('rel_financeiro_fatenviadas','Faturas Enviadas', 'Relatórios'),
('rel_clientes_uf','Cliente por UF', 'Relatórios'),
('rel_resumo_veic_disponiveis','Resumo Veiculos Disponiveis', 'Relatórios'),
('rel_veic_disponiveis','Veiculos Disponiveis', 'Relatórios'),
('rel_dash_veic','Dashboard Veiculos', 'Relatórios'),
('rel_monitorados_dia_atividade','Monitorados por dia de atividade', 'Relatórios'),
('contratos_cancelar','Cancelar', 'Contratos'),
('edit_contrato Editar','Vendedor', 'Contratos'),
('downloads_contratos','Downloads', 'Contratos'),
('admin_permissoes','Administrador', 'Administração'),
('observador_permissoes','Observador', 'Administração'),
('dashboard_iscas','Dashboard', 'Administrativo Iscas'),
('equipamentos_iscas','Equipamentos Iscas', 'Administrativo Iscas'),
('relatorios_iscas','Relatórios Iscas', 'Administrativo Iscas'),
('comandos_iscas','Comandos Iscas', 'Administrativo Iscas'),
('financeiro_acesso','Financeiro', 'Financeiro'),
('inadimplencias_faturas','Inadimplências', 'Financeiro'),
('compras','Compras', 'Financeiro'),
('faturas','Faturas', 'Faturas'),
('faturas_visualiza','Visualizar Faturas', 'Faturas'),
('faturas_add','Adicionar Faturas', 'Faturas'),
('faturas_update','Atualizar Faturas', 'Faturas'),
('faturaACancelar','Cancelar Faturas', 'Faturas'),
('faturas_delete','Deletar faturas', 'Faturas'),
('faturas_retorno','Retorno Faturas', 'Faturas'),
('config_boleto','Conf. boleto', 'Faturas'),
('edit_tipo_faturamento','Editar tipo faturamento', 'Faturas'),
('chave_desconto','Chave de desconto', 'Chave de Desconto'),
('criar_chave_desconto','Criar chave de desconto', 'Chave de Desconto'),
('listar_chave_desconto','Listar chave de desconto', 'Chave de Desconto'),
('contas_a_pagar','Contas', 'Contas'),
('aprovador','Aprovador', 'Contas'),
('lancamentos','Ordem de Pagamentos (OP)', 'Contas'),
('contas_showtecnologia','ShowTecnologia', 'Contas'),
('contas_eua','ShowTechnology', 'Contas'),
('contas_pneushow','Pneu Show', 'Contas'),
('valores','Valores', 'Contas'),
('cancelar_conta','Cancelar Conta', 'Contas'),
('baixa_extrato_show','Baixa extrato Show', 'Baixa por Extrato'),
('baixa_extrato_norio','Baixa exrtato Norío', 'Baixa por Extrato'),
('visualizar_tickets','Tickets', 'Suporte'),
('downloads_os','Downloads OS', 'Suporte'),
('veiculos_desatualizados','Desatualizados', 'Suporte'),
('logs','Logs', 'Suporte'),
('api',' API', 'Desenvolvimento'),
('monitoramento','Monitoramento', 'Monitoramento'),
('equipamentos_violados','Equipamentos violados', 'Monitoramento'),
('monitor_panico','Pânico', 'Monitoramento'),
('gateways','Gateways', 'Monitoramento'),
('monitor_contrato','Monitoramento Contratos', 'Monitoramento'),
('configuracoes','Configuração', 'Configuração'),
('mensagem_notificacao','SMS', 'Configuração'),
('add_termo','Adicionar', 'Termo de Adesão'),
('edit_termo','Editar', 'Termo de Adesão'),
('print_termo','Imprimir', 'Termo de Adesão'),
('admin_termo','Admin Termo de adesão', 'Termo de Adesão'),
('zoiper','Zoiper', 'Atalhos'),
('edools','Edools', 'Atalhos'),
('pipedrive','PipeDrive', 'Atalhos'),
('trello','Trello', 'Atalhos'),
('crm_omnilink','CRM OMNILINK', 'Atalhos'),
('omniweb','OMNIWEB', 'Atalhos'),
('iridium','IRIDIUM', 'Atalhos'),
('turbo','TURBO - SAVERNET', 'Atalhos'),
('omniturbo','OMNITURBO - SAVERNET', 'Atalhos'),
('painel_ativ','PAINEL DE ATIVAÇÃO', 'Atalhos'),
('andromeda','ANDRÔMEDA - APN', 'Atalhos'),
('mhs','MHS - MR', 'Atalhos'),
('telemetria','TELEMETRIA - CAN', 'Atalhos'),
('protheus','WEB PROTHEUS', 'Atalhos'),
('srv','SVR - WEBGRABER', 'Atalhos'),
('omnitelemetria2','OMNITELEMETRIA 2.0', 'Atalhos'),
('pedidos', 'Pedidos', 'Televendas');
