
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNDE3MDQ0MzYtZWFkMS00ZGFhLTljNjktMDNhNjU0ZjNkOTY3IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=prestadores_bi' WHERE nome = 'prestadores_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiZDA2MzczM2EtZmE3ZS00MWIzLWJiZjUtYjUxMjUwNmMyM2EzIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=abertura_na_bi' WHERE nome = 'abertura_na_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYzViN2E1M2MtM2ExYi00YzAzLWE2MGYtNjJmMDg5ZjAxOTNjIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=atividade_servico_bi' WHERE nome = 'atividade_servico_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMGQ2NmRlODgtZTk1Zi00OTA0LTgwYTUtNzNiZTMxMWFlMTZkIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=gestao_agendamento_bi' WHERE nome = 'gestao_agendamento_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNGI3YzJkYzktNjA2NC00MjBlLTgyZmItMmFlNDNjZjc1YjlhIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=desempenho_bi' WHERE nome = 'desempenho_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiOGJjZmQ3NGYtMjc4NS00YTUxLTk4MzYtZTc4YWFkYWYwNjQ3IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=painel_atendimento_bi' WHERE nome = 'painel_atendimento_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYmMyN2Y4NTAtM2VjZC00ZTU5LTljN2UtOTAzODY5YjgwZjgzIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=produtividade_bi' WHERE nome = 'produtividade_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYTI2OGMxOTYtN2I4YS00ODI5LWEwMTctNWM5Njk4ZGVhMjAyIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=painel_operacoes_bi' WHERE nome = 'painel_operacoes_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiZWYxNjU4YTctMzMyMy00YWI0LTg0OWUtOTAzNmYyMjY3NmU1IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=analitico_clientes_bi' WHERE nome = 'analitico_clientes_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiZWIzZDZjZWEtNzIzNS00ZmYzLThlY2MtNmJkNzdhYjlhOWQ5IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=gestao_retencao_bi' WHERE nome = 'gestao_retencao_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYjc0NDJiOTEtMGJkZi00NDc2LWIxODUtOTE2ZjZkZTQ5MjdjIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=churn_bi' WHERE nome = 'churn_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiN2I0NmJiNGItZTFkNC00ODQ3LThlMGQtMGJlMzM2Y2Q5NTgxIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=chatbot_bi' WHERE nome = 'chatbot_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNDQxZWM4YzYtOGQ3ZS00NzhjLTlmYjQtYzIxM2FhY2JiYTRiIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=chatbot_crm_bi' WHERE nome = 'chatbot_crm_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMjIwOTIzYjgtNGVkMy00ZTU4LTk2NzItYWNkOGU0OThmN2U0IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=homologacao_bi' WHERE nome = 'homologacao_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiOWIxZDZjYWItNTZmMC00NDdhLWI3ZWItZjhhZDM2OGJkY2RmIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=monitoria_bi' WHERE nome = 'monitoria_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNGZjMjM4NjktNGJkYS00NGY2LWFlNTAtNWVhMmQ4MzZhZjIxIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=treinamento_bi' WHERE nome = 'treinamento_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMDExZTE3N2YtNDA1Ni00MjcwLTk2NDMtZDAxNmRiOGQ3N2Y2IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=atendimentos_cidade_bi' WHERE nome = 'atendimentos_cidade_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMzBjZDhlZmMtNzdkNi00NDE1LWI5YTMtYWEyMTNmNTExZDc0IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=painel_indisponibilidade' WHERE nome = 'painel_indisponibilidade'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiM2ViYjVkYWUtMzZmYi00ZTYxLWJjMDktNzYxOGQyN2FiMTVkIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=resultados_operacoes_bi' WHERE nome = 'resultados_operacoes_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMTk4NzdmOGEtNTk1OC00ZjViLWExMDUtNDBlN2ViZTQyMTg0IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=telemetria_can_bi' WHERE nome = 'telemetria_can_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYzdkZmU5OTctZTEzOS00ZTYzLTgxMzEtMDEzZmYwNjA3NWFlIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=segmentacao_clientes_bi' WHERE nome = 'segmentacao_clientes_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiMzBjZDhlZmMtNzdkNi00NDE1LWI5YTMtYWEyMTNmNTExZDc0IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=painel_indisponibilidade_bi' WHERE nome = 'painel_indisponibilidade_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiZTBmODIwNjUtY2MyMC00Y2U3LWI0MzMtY2M3NDQwNWEwZDI1IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=gestao_command_center_bi' WHERE nome = 'gestao_command_center_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNzFmMmY1ZGQtNDNjNy00MjMwLTk5YzItZWYwODM1MDIxY2JhIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=acompanhamento_af_bi' WHERE nome = 'acompanhamento_af_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNGMxMDY4YTEtZjM4MS00Njg1LTliMjYtZGVkMzU0ZWNiNzQwIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=telecom_bi' WHERE nome = 'telecom_bi'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNWY2NTVhOTctNWE0Yy00ZTJlLWEwOGYtMDVkMjcxMDVjYzg4IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=telemetria_can' WHERE nome = 'telemetria_can'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiYzdkZmU5OTctZTEzOS00ZTYzLTgxMzEtMDEzZmYwNjA3NWFlIiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&menu_nome=segmentacao_clientes' WHERE nome = 'segmentacao_clientes'
UPDATE showtecsystem.menu SET link_bi = 'https://app.powerbi.com/view?r=eyJrIjoiNDYxNzZjMTgtZDUxZC00NDM5LTliYmUtMzk3YTJkZTY5Mjg5IiwidCI6ImFiODlkOGJjLTFlZjQtNGU3ZC1iMGNlLWM0M2ZiZmRmYWNlMyJ9&pa&menu_nome=consulta_af_e_rede' WHERE nome = 'Consulta AF e Rede'





