INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_veiculos','Veículos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_permissoes','Permissões (GESTOR)');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_planos Planos','(GESTOR)');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('administrar_veiculos','Administrar Veículos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_equipamento','Equipamentos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_contratos_eptc','Contratos EPTC');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_agend_servico','Agendamento de Serviços');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_instaladores','Instaladores');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cadastro_fornecedor','Fornecedores');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_representantes','Representantes');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_comandos','Comandos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('clientes_visualiza','Visualizar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('clientes_add','Adicionar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('clientes_update','Atualizar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('inativa_clie','Inativar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('clientes_bloqueio','Bloqueio usuário');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('clientes_arquivo','Download Arquivos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('usuarios_visualiza','Visualizar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('usuarios_add','Adicionar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('usuarios_update','Atualizar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('status_funcionario','Status funcionario'); 
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('aplicar_ferias','Aplicar ferias');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('demitir','Demitir');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('m2m','M2M');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('crm_vendas','crm_vendas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('crm_vendas_admin','Administrador');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_linhas','Linhas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_mikrotik','MikroTik');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_chips','Chips');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_rh','RH');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_aniversariantes','Aniversariantes');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_apresentacoes','Apresentações');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_banner','Banner');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_comunicado','Comunicados');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_contatos_corporativos','Contatos Corporativos');   
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_folhetos','Folhetos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_sobre_empresa','Sobre a empresa');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_politicas_formularios','Políticas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_produtos','Produtos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_suporte_tecnico','Suporte Técnico');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_teste_homologacao','Teste e Homologação');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_espaco_ti','Espaço TI');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_marketing_briefing','Briefing');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_marketing_campanhas','Campanhas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_apresentacoes_comerciais','Apresentações Comerciais');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_comite_guerra','Comitê de Guerra');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_televendas_comunicados','Comunicados');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_propostas_comerciais','Propostas Comerciais');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_politicas_procedimentos','Políticas e Procedimentos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_guia_produtos','Guia de Produtos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_precos_acessorios','Tabela de Preços e Acessórios');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_inteligencia_mercado','Inteligência de Mercado');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_governanca_corporativa','Governança Corporativa');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_gente_gestao','Gente e gestão');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_treinamentos','Treinamentos EAD');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_atividades','Cad Treinamentos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_parcerias','Parcerias');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_plano_de_voo','Plano de Voo');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_correcao_irrf','Correção de IRRF');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_docs_pendentes','Documentos Pendentes');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cad_desconto_coparticipacao','Desconto de Coparticipação');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_tipo_servico','Tipo de Serviços');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_veic_tempo_contrato','Veículo por Tempo de Contrato');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_clients_publicos','Clientes Públicos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_contas','Contas a Pagar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_contratos','Contratos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_placas_ativas_inativas','Placas Ativas - Inativas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_tempo_logado','Tempo logado');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_envio_sms','Envio SMS');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_eqp_desat','Equipamentos Desatualizados');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('analise_contaOp','Analise de Fatura Operadora');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_financeiro_faturas','Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('comissao','Comissionamento de Vendedores');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('comissao_showroutes','Comissionamento - ShowRoutes');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_adesao','Relatorio de adesao');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_financeiro_fatenviadas','Faturas Enviadas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_clientes_uf','Cliente por UF');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_resumo_veic_disponiveis','Resumo Veiculos Disponiveis');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_veic_disponiveis','Veiculos Disponiveis');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_dash_veic','Dashboard Veiculos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('contratos_cancelar','Cancelar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('edit_contrato Editar','Vendedor');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('downloads_contratos','Downloads');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('admin_permissoes','Administrador');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('observador_permissoes','Observador');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('dashboard_iscas','Dashboard');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('equipamentos_iscas','Equipamentos Iscas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('relatorios_iscas','Relatórios Iscas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('comandos_iscas','Comandos Iscas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('financeiro_acesso','Financeiro');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('inadimplencias_faturas','Inadimplências');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('compras','Compras');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas','Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas_visualiza','Visualizar Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas_add','Adicionar Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas_update','Atualizar Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturaACancelar','Cancelar Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas_delete','Deletar faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('faturas_retorno','Retorno Faturas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('config_boleto','Conf. boleto');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('edit_tipo_faturamento','Editar tipo faturamento');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('chave_desconto','Chave de desconto');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('criar_chave_desconto','Criar chave de desconto');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('listar_chave_desconto','Listar chave de desconto');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('contas_a_pagar','Contas');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('aprovador','Aprovador');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('lancamentos','Ordem de Pagamentos (OP)');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('contas_showtecnologia','ShowTecnologia');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('contas_eua','ShowTechnology');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('contas_pneushow','Pneu Show');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('valores','Valores');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('cancelar_conta','Cancelar Conta');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('baixa_extrato_show','Baixa extrato Show');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('baixa_extrato_norio','Baixa exrtato Norío');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('visualizar_tickets','Tickets');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('downloads_os','Downloads OS');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('veiculos_desatualizados','Desatualizados');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('logs','Logs');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('api',' API');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('monitoramento','Monitoramento');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('equipamentos_violados','Equipamentos violados');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('monitor_panico','Pânico');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('gateways','Gateways');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('monitor_contrato','Monitoramento Contratos');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('configuracoes','Configuração');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('mensagem_notificacao','SMS');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('add_termo','Adicionar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('edit_termo','Editar');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('print_termo','Imprimir');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('admin_termo','Admin Termo de adesão');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('zoiper','Zoiper');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('edools','Edools');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('pipedrive','PipeDrive');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('trello','Trello');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('crm_omnilink','CRM OMNILINK');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('omniweb','OMNIWEB');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('iridium','IRIDIUM');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('turbo','TURBO - SAVERNET');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('omniturbo','OMNITURBO - SAVERNET');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('painel_ativ','PAINEL DE ATIVAÇÃO');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('andromeda','ANDRÔMEDA - APN');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('mhs','MHS - MR');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('telemetria','TELEMETRIA - CAN');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('protheus','WEB PROTHEUS');                       
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('srv','SVR - WEBGRABER');                      
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('omnitelemetria2','OMNITELEMETRIA 2.0');
INSERT INTO `showtecsystem`.`cad_permissoes_funcionarios` (`cod_permissao` , `descricao`) values ('rel_monitorados_dia_atividade','Monitorados por dia de atividade');